# This file is automatically generated by Flutter
# Do not edit manually

FLUTTER_ROOT = ENV['FLUTTER_ROOT'] || File.expand_path('../../../../../../Developer/flutter', __FILE__)
require File.join(FLUTTER_ROOT, 'packages', 'flutter_tools', 'bin', 'podhelper.rb')

