# Uncomment this line to define a global platform for your project
platform :ios, '12.0'

# CocoaPods analytics sends metrics to their servers
# to help improve CocoaPods and other tools.
# Use of analytics requires opt out by using the flag `--no-analytics`.
use_frameworks! :linkage => :static

# Enables Flipper.
#
# Note that if you have use_frameworks! enabled, Flipper will not work and
# you should disable the next line.
# use_flipper!
# Post Install processing
def flutter_post_install(installer)
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end

target 'Runner' do
  use_frameworks! :linkage => :static
  use_modular_headers!

  # Flutter Pods
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  flutter_post_install(installer)
end
