# Uncomment this line to define a global platform for your project
platform :ios, '15.0'

# Load Flutter podhelper functions
FLUTTER_ROOT = ENV['FLUTTER_ROOT'] || '/Users/ibraheem.designer/Developer/flutter'
require File.join(FLUTTER_ROOT, 'packages', 'flutter_tools', 'bin', 'podhelper.rb')

# CocoaPods analytics sends metrics to their servers
# to help improve CocoaPods and other tools.
# Use of analytics requires opt out by using the flag `--no-analytics`.
use_frameworks! :linkage => :static

# Enables Flipper.
#
# Note that if you have use_frameworks! enabled, Flipper will not work and
# you should disable the next line.
# use_flipper!

target 'Runner' do
  use_frameworks! :linkage => :static
  use_modular_headers!

  # Flutter Pods
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
      config.build_settings['ENABLE_BITCODE'] = 'NO'
      
      # إصلاح تحذيرات deprecation و warnings
      config.build_settings['GCC_WARN_INHIBIT_ALL_WARNINGS'] = 'YES'
      config.build_settings['SWIFT_SUPPRESS_WARNINGS'] = 'YES'
      config.build_settings['CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER'] = 'NO'
      
      # إصلاح مشكلة FirebaseCore headers
      if target.name == 'FirebaseCore'
        config.build_settings['CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER'] = 'NO'
      end
      
      # إصلاح مشكلة firebase_core incompatible pointer
      if target.name.include?('firebase_core') || target.name.include?('Firebase')
        config.build_settings['CLANG_WARN_OBJC_IMPLICIT_RETAIN_SELF'] = 'NO'
      end
    end
  end
end
